language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t huulam/udagram-api-feed ./udagram-api-feed
  - docker build -t huulam/udagram-api-user ./udagram-api-user
  - docker build -t huulam/udagram-frontend ./udagram-frontend
  - docker build -t huulam/reverseproxy ./udagram-reverseproxy
#tag
  - docker tag huulam/udagram-api-feed huulam/udagram-api-feed:latest
  - docker tag huulam/udagram-api-user huulam/udagram-api-user:latest
  - docker tag huulam/udagram-frontend huulam/udagram-frontend:latest
  - docker tag huulam/reverseproxy huulam/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push huulam/udagram-api-feed 
  - docker push huulam/udagram-api-user 
  - docker push huulam/udagram-frontend 
  - docker push huulam/reverseproxy