apiVersion: v1
kind: Service
metadata:
  name: backend-user
spec:
  selector:
    app: backend-user
  ports:
    - name: backend-user
      protocol: TCP
      port: 8080
      targetPort: 8080
