apiVersion: v1
kind: Service
metadata:
  name: backend-feed
spec:
  selector:
    app: backend-feed
  ports:
    - name: backend-feed
      protocol: TCP
      port: 8080
      targetPort: 8080