apiVersion: v1
kind: Service
metadata:
  name: frontend-app-svc
spec:
  selector:
    app: frontend-app
  ports:
    - name: frontend-app-svc
      protocol: TCP
      port: 8080
      targetPort: 8080
