apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-app-svc
spec:
  selector:
    app: reverseproxy-app
  ports:
    - name: reverseproxy-app-svc
      protocol: TCP
      port: 8080
      targetPort: 8080